sudo: required
dist: trusty
language: cpp
cache: ccache
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-9
    - gcc-9
    - libglu1-mesa-dev
    - libgmp-dev
    - libboost-all-dev
    - libmpfr-dev
    - xorg-dev
  homebrew:
    packages:
    - suite-sparse
    - ccache
matrix:
  include:
  - os: linux
    compiler: gcc-9
    env:
    - MATRIX_EVAL="export CC=gcc-9 && CXX=g++-9 && CONFIG=Debug"

  - os: linux
    compiler: gcc-9
    env:
    - MATRIX_EVAL="export CC=gcc-9 && CXX=g++-9 && CONFIG=Release"

  - os: osx
    osx_image: xcode11.1
    compiler: clang
    env:
    - MATRIX_EVAL="export CONFIG=Debug"

  - os: osx
    osx_image: xcode11.1
    compiler: clang
    env:
    - MATRIX_EVAL="export CONFIG=Release"

install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH="/usr/local/opt/ccache/libexec:$PATH"; fi
- eval "${MATRIX_EVAL}"
# - ccache --max-size=5.0G
# - ccache -V && ccache --show-stats && ccache --zero-stats

script:
- mkdir build
- cd build
- cmake -DCMAKE_BUILD_TYPE=$CONFIG ${EXTRA_FLAGS} ..
- make -j2
# - if [[ "$CONFIG" == "Release" ]]; then make test; fi
# - ccache --show-stats
